version:	"3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - database:/dbdata
    restart: "no"
    ports:
      - "3306"
  nginx:
    build: ./requirements/nginx
    restart: "no"
    ports:
      - "443"
    volumes:
      - wordpress_web:/conf
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: "no"
    ports:
      - "9000"
    volumes:
      - wordpress_web:/files
volumes:
  wordpress_web:
    driver: local
    driver_opts:
      device: /home/jhille/data/wordpress
      o: bind
  database:
    driver: local
    driver_opts:
      device: /home/jhille/data/database
      o: bind

