version:	"3.8"

services:
  mariadb:
    build: "./requirements/mariadb"
    volumes:
      - "./requirements/mariadb/conf:/dbdata"
    restart: "no"
  nginx:
    build: "./requirements/nginx"
    restart: "no"
    ports:
      - "8081:80"
    volumes:
      - "./requirements/nginx/conf:/conf"
  wordpress:
    depends_on:
      - "mariadb"
    build: "./requirements/wordpress"
    restart: "no"

