version:	"3.8"

services:
  mariadb:
    build: "./requirements/mariadb"
    volumes:
      - "./requirements/mariadb/conf:/dbdata"
    restart: "no"
    ports:
      - "3306"
  nginx:
    build: "./requirements/nginx"
    restart: "no"
    ports:
      - "443"
    volumes:
      - wp:/conf
  wordpress:
    depends_on:
      - "mariadb"
    build: "./requirements/wordpress"
    restart: "no"
    ports:
      - "9000"
    volumes:
      wp:/files
volumes:
  wp:
