version:	"3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nginx:
    build: ./requirements/nginx
    restart: "no"
    ports:
      - "443"
    volumes:
      - wordpress_web:/webfiles
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: "no"
    volumes:
      - wordpress_web:/files
volumes:
  wordpress_web:
    driver: local
    driver_opts:
      o: bind
      type: none
      #device: /home/jhille/data/wordpress
      device: /Users/jhille/projects/inception/inception-42/website
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      #device: /home/jhille/data/database
      device: /Users/jhille/projects/inception/inception-42/data
