version:	"3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - database:/dbdata
    restart: "no"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT:${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
  nginx:
    build: ./requirements/nginx
    restart: "no"
    ports:
      - "443"
    volumes:
      - wordpress_web:/webfiles
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: "no"
    ports:
      - "9000"
    volumes:
      - wordpress_web:/files
volumes:
  wordpress_web:
    driver: local
    driver_opts:
      type: nfs
      #device: /home/jhille/data/wordpress
      device: /Users/jhille/projects/inception/wordpress_web
      o: bind
  database:
    driver: local
    driver_opts:
      type: nfs
      #device: /home/jhille/data/database
      device: /Users/jhille/projects/inception/database
      o: bind
