FROM alpine:3.16


# Install persistent dependencies
RUN apk upgrade
RUN apk add php8 \
        php8-curl \
        php8-dom \
        php8-exif \
        php8-fileinfo \
        php8-pecl-mcrypt \
        php8-pecl-imagick